language: php

php:
  - 5.6
  - 7

services:
  - mysql

before_script:
  - composer self-update
  - mysql -e 'create database instante collate utf8_general_ci; create database instante_test collate utf8_general_ci;'

script: ./tests/skeleton-test.sh
